//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubLeagues.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClub
    {
        public int id { get; set; }
        public int UserId { get; set; }
        public int ClubId { get; set; }
        public byte[] rowversion { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual User User { get; set; }
    }
}
